import {
  IconAlertTriangle,
  IconArrowRight,
  IconArrowsRightLeft,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconShield,
  IconLock,
  IconBabyCarriage,
  IconIdBadge2,
  IconHome,
  IconUsersGroup,
  IconCertificate,
  IconGrave2,
  IconEdit,
  IconInbox
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconBox,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  arrowsRightLeft: IconArrowsRightLeft,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  shield: IconShield,
  lock: IconLock,
  baby: IconBabyCarriage,
  idCard: IconIdBadge2,
  home: IconHome,
  family: IconUsersGroup,
  certificate: IconCertificate,
  grave: IconGrave2,
  edit: IconEdit,
  inbox: IconInbox
};
